version: '3'
services:
  primary:
    build: .
    volumes:
      - afl-results:/results
    entrypoint: /usr/local/bin/afl-fuzz
    command: [ "-i", "/app/tests", "-o", "/results", "-M", "primary", "/app/maybe-crash"]

  # Secondary instances can be used to parallelise a job.
  # It is necessary that they maintain access to the same output directory (/results).
  # Note the differing arguments for '-S' - these are the identifiers for each secondary fuzzer.
  # There is currently no way to use the '--scale' option to create containers with accessible unique identifiers.
  secondary-01:
    build: .
    volumes:
      - afl-results:/results
    entrypoint: /usr/local/bin/afl-fuzz
    command: [ "-i", "/app/tests", "-o", "/results", "-S", "secondary-01", "/app/maybe-crash"]
  secondary-02:
    build: .
    volumes:
      - afl-results:/results
    entrypoint: /usr/local/bin/afl-fuzz
    command: [ "-i", "/app/tests", "-o", "/results", "-S", "secondary-02", "/app/maybe-crash"]

volumes:
  # Use the following to locate the directory:
  #   docker volume inspect afl-results | jq '.[] | .Mountpoint'
  # or docker-cp from an existing container using it.
  afl-results:
